### ISSUE TITLE
后台程序多开问题

### ISSUE THREAD

**Issue by Mercury223** [HofNature/SRunPy-GUI#1]
感谢作者！在使用中遇到一个小问题，因为有远程控制的需求，害怕程序被杀后台，所以在Windows 任务计划程序中添加了一定时间后重复启动，每半个小时启动一次程序，避免被杀后台。但是程序会出现多开的情况，即后台出现多个程序图标，请问作者能否解决这一问题？不胜感激！

**Comment by HofNature** [comment]
在任务计划程序中设置“如果此任务已经运行，请勿启动新实例”是否有效？

**Comment by Mercury223** [comment]
感谢回复！默认设置就是您所说的已运行请勿启动，并无效果
![微信图片_20240816154746](https://github.com/user-attachments/assets/a536e886-b57a-46a4-8e9f-7533451d0826)

**Comment by HofNature** [comment]
过会儿我修改一下

**Comment by Mercury223** [comment]
感谢大佬！

**Comment by HofNature** [comment]
已经弄好了
